services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - new_network

  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - new_network
    depends_on:
      - mongodb
      - python-service
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/CyberDetective
      - PYTHON_URI=python-service:5000

  python-service:
    build: ./python-service
    container_name: python-service
    ports:
      - "5000:5000"
    networks:
      - new_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - new_network
    volumes:
      - mongo-data:/data/db

networks:
  new_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
